In [1]:
from scholarly import scholarly
import pandas as pd

In [2]:
def getAvgCiteRate(pubs):
    rateDict = pubs.cites_per_year
    rateList = [rateDict[key] for key in rateDict]
    return sum(rateList)/len(rateList)

def getNumPubs(dfRow, debug=False):
    prof = dfRow['Name']
    
    try:
        # Query Google Scholar for the prof and get their profile
        search_query = scholarly.search_author(prof)
        author = next(search_query)

        # Get publication stats
        pubs = author.fill(sections=['counts'])

        # Calculate citation rate [cites/year]
        citeRate = getAvgCiteRate(pubs)
    except:
        # If this runs into an error, set rate to -1 to indicate
        # that something went wrong
        citeRate = -1
    if debug:
        print(prof, citeRate)
    return citeRate

In [3]:
profs = pd.read_csv('profnames.txt')

In [4]:
# Run queries and add average cite rate to new column
profs['avgCiteRate'] = profs.apply(getNumPubs, axis=1)

Marco Alfano 19.4
Arash Arami 191.7
Sanjeev Bedi 119.08
Elliot Biro 85.88235294117646
Clifford Butcher 63.53846153846154
Dongpu Cao 394.2142857142857
Naveen Chandrashekar -1
Michael Collins 970.375
Duane Cronin 166.68421052631578
Richard J Culham -1
Kyle Daun 121.94736842105263
Cecile Devaud 38.666666666666664
Kaan Erkorkmaz 148.68421052631578
Shahrzad Esmaeili 140.61111111111111
Baris Fidan 598.4
Roydon Fraser -1
Adrian Gerlich 394.2
Kamyar Ghavam -1
Allyson Giannikouris -1
Feridun Hamdullahpur -1
Carolyn Hansson 114.54545454545455
Jean-Pierre Hickey 40.55555555555556
Jan Huissoon 62.23076923076923
Carol Hulls 7.066666666666666
Kaan Inal 94.57894736842105
Hamid Jahedmotlagh -1
Soo Jeon 189.3
David Johnson 5913.820512820513
Amir Khajepour 494.1111111111111

In [7]:
profs

                    Name  avgCiteRate
0           Marco Alfano    19.400000
1            Arash Arami   191.700000
2           Sanjeev Bedi   119.080000
3            Elliot Biro    85.882353
4       Clifford Butcher    63.538462
5             Dongpu Cao   394.214286
6   Naveen Chandrashekar    -1.000000
7        Michael Collins   970.375000
8           Duane Cronin   166.684211
9       Richard J Culham    -1.000000
10             Kyle Daun   121.947368
11         Cecile Devaud    38.666667
12        Kaan Erkorkmaz   148.684211
13     Shahrzad Esmaeili   140.611111
14           Baris Fidan   598.400000
15         Roydon Fraser    -1.000000
16        Adrian Gerlich   394.200000
17         Kamyar Ghavam    -1.000000
18  Allyson Giannikouris    -1.000000
19  Feridun Hamdullahpur    -1.000000
20       Carolyn Hansson   114.545455
21    Jean-Pierre Hickey    40.555556
22          Jan Huissoon    62.230769
23           Carol Hulls     7.066667
24             Kaan Inal    94.578947
25    Hamid Jahedmotlagh    -1.000000
26              Soo Jeon   189.300000
27         David Johnson  5913.820513
28        Amir Khajepour   494.111111