Searches Google for faculty pages.

In [78]:
from googlesearch import search
import pandas as pd

# Import university dataframe
data = pd.read_csv('uni_data.csv')

# Grab first 10 only
data = data[0:10]

In [79]:
data

,name,locality,state,country,url
0,Massachusetts Institute of Technology,"Cambridge, Massachusetts",NaN,United States,https://web.mit.edu/
1,Harvard University,Cambridge,Massachusetts,United States,http://harvard.edu
2,Stanford University,Stanford,California,United States,http://stanford.edu
3,"University of California, Berkeley",Berkeley,California,United States,http://www.berkeley.edu
4,Purdue University,West Lafayette,Indiana,United States,http://www.purdue.edu
5,Cornell University,Ithaca,New York,United States,http://cornell.edu
6,University of Washington,Seattle,Washington,United States,http://www.washington.edu
7,Columbia University in the City of New York,New York City,New York,United States,http://columbia.edu
8,University of Michigan,Ann Arbor,Michigan,United States,http://www.umich.edu
9,Penn State University,University Park,Pennsylvania,United States,http://www.psu.edu

In [80]:
# General search terms
faculties = ['engineering', 'physics', 'astronomy', 'arts', 'biology', 'chemistry']
targetTerms = ['people', 'faculty', 'professors', 'group']
targetTerms = ' OR '.join(targetTerms)

def getStaffPages(dfRow, faculty):
    query = faculty + ' ' + targetTerms + ' site:' + dfRow['url']
    results = [x for x in search(query, lang = 'en', start = 0, stop = 20, pause = 2.0)]
    return results

getStaffPagesForFaculty = lambda dfRow: getStaffPages(dfRow, faculties[1])

for i, row in data.iterrows():
    try:
        row['search results'] = getStaffPagesForFaculty(row)
    except:
        print('Probably error 429')

Probably error 429
Probably error 429
Probably error 429
Probably error 429
Probably error 429
Probably error 429
Probably error 429
Probably error 429
Probably error 429
Probably error 429